/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentRouteImport } from './routes/present'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedIdRouteImport } from './routes/shared.$id'

const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIdRoute = SharedIdRouteImport.update({
  id: '/shared/$id',
  path: '/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lesson': typeof LessonRoute
  '/present': typeof PresentRoute
  '/shared/$id': typeof SharedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson': typeof LessonRoute
  '/present': typeof PresentRoute
  '/shared/$id': typeof SharedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lesson': typeof LessonRoute
  '/present': typeof PresentRoute
  '/shared/$id': typeof SharedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lesson' | '/present' | '/shared/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lesson' | '/present' | '/shared/$id'
  id: '__root__' | '/' | '/lesson' | '/present' | '/shared/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonRoute: typeof LessonRoute
  PresentRoute: typeof PresentRoute
  SharedIdRoute: typeof SharedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$id': {
      id: '/shared/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonRoute: LessonRoute,
  PresentRoute: PresentRoute,
  SharedIdRoute: SharedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
